name: rathod
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  jobglu_job:
    runs-on: ubuntu-latest
    environment:
      name: testing
    steps:
      - name: Are You an User ?
        run: echo Hello ${{ github.actor }} 

      - name: Pulling Git Repository
        uses: actions/checkout@v4

      - name: Login into Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.dev
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/rathod:latest
          cache-from: type=gha
          cache-to: type=gha, mode=max
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
